@baseurl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseurl}}/accounts
content-Type: application/json

{
    "name": "example",
    "email": "example@example.com.br",
    "password": "umasenhamuitoforte"
}


###


# @name authenticate
POST {{baseurl}}/sessions
Content-Type: application/json

{
    "email": "example@example.com.br",
    "password": "umasenhamuitoforte"
}

###

# @name question
POST {{baseurl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "nova pergunta 2",
    "content": "Conteudo da pergunta"
}

###

# @name fetch-recent-question
GET {{baseurl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get-question-by-lug
GET {{baseurl}}/questions/nova-pergunta-3
Content-Type: application/json
Authorization: Bearer {{authToken}}